### PR TITLE
Add a link to the cheat sheet in Learn

### PR DESCRIPTION
**Pull request by aturley**
This adds a link to the Pony Cheat Sheet on the Learn page so that
beginners can find the cheat sheet and start to use it to help them
learn.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
Thoughts on hosting the cheat sheet on ponylang.org @aturley ? If you are comfortable with that, I'd rather do that.

**Comment by aturley** [comment]
Sure, I can do that.

**Comment by aturley** [comment]
@SeanTAllen added.

**Comment by SeanTAllen** [comment]
Thanks!

**Pull request merged**
