### PR TITLE
Create this-week-in-pony-04417.md

### PR DESCRIPTION
**Pull request by insanitybit**
This is the TWIP for this week. Apologies for the delay - have to ship it from my office this week.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I'm going to merge this when it passes. I think in future for RFC sections, if they are empty we should either have a note or probably even better, remove the section. Thoughts @insanitybit?

**Comment by insanitybit** [comment]
I think a note is the way to go - that's what I did for the last issue, but missed it this time. I can modify this PR to include a "There were no XYZ this week" in the right places?

**Comment by SeanTAllen** [comment]
Ill do as part of the cleanup we discussed on IRC.

**Comment by SeanTAllen** [comment]
Thanks @insanitybit

**Pull request merged**
