### PR TITLE
Adds some example code to the landing page, with links to documentation and the playground.

### PR DESCRIPTION
**Pull request by kulibali**
I often see people complaining about programming language sites that don't have sample code up front.

This is just an example of what we could do.  It's a silly FizzBuzz program implemented with actors, with links to the playground and documentation.

image

### CODE REVIEW

**Comment by SeanTAllen** [comment]
Thanks for this @kulibali. I don't believe this belongs on the front page but should be worked into the Discover section somehow.

**Comment by kulibali** [comment]
I was imitating [Rust](https://www.rust-lang.org/en-US/), which has runnable code on the front page.

**Comment by SeanTAllen** [comment]
@kulibali highlight.js is already included on the site.

**Comment by SeanTAllen** [comment]
The site is using pixels in the theme and mixing in `em` based measures seem like a bad idea.

**Comment by kulibali** [comment]
Will close this pending further discussion, especially since I forgot to make a separate branch.

**Pull request closed without merging**
